//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kabab_TakeAway
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KebabTakeawayEntities1 : DbContext
    {
        public KebabTakeawayEntities1()
            : base("name=KebabTakeawayEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<drink> drinks { get; set; }
        public virtual DbSet<email> emails { get; set; }
        public virtual DbSet<kebab> kebabs { get; set; }
        public virtual DbSet<maintb> maintbs { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
