//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kabab_TakeAway
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string password { get; set; }
        public Nullable<int> E_id { get; set; }
    
        public virtual email email { get; set; }
    }
}
